<?php
/**
 * Shortener Interface, outlines methods required for a valid shorten object.
 *
 * @package UtmDotCodes
 */

namespace UtmDotCodes;

/**
 * Interface Shorten.
 */
interface Shorten {

	/**
	 * Shortener method for the class.
	 *
	 * @param array  $data Array of post data containing associative utm input values, or Array of post data
	 * containing meta_input array with associative utm input values.
	 * @param string $query_string Prepared query string of link being shortened.
	 *
	 * @return void
	 */
	public function shorten( $data, $query_string );

	/**
	 * Shortened URL provided by API for the provided request using the configured credentials.
	 *
	 * @return mixed
	 */
	public function get_response();

	/**
	 * Error code response generated by the request to the API.
	 *
	 * @return mixed
	 */
	public function get_error();

}
