name: Code Styles

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
    types: [closed]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  code-styles:
    name: WordPress ${{ matrix.wordpress-versions }} - PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-versions: [ '8.2' ]
        wordpress-versions: [ '6.2' ]
        operating-system: [ ubuntu-22.04 ]

    steps:
      - name: Setup PHP
        # Commit hash for v2.25.4: https://github.com/shivammathur/setup-php/releases/tag/2.25.4
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug

      - name: Checkout utm.codes
        # Commit hash for v3.5.3: https://github.com/actions/checkout/releases/tag/v3.5.3
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Setup PHPCS
        run: |
          composer install
          ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
          ./vendor/bin/phpcs --config-set ignore_errors_on_exit 1
          ./vendor/bin/phpcs --config-set show_progress 1
          ./vendor/bin/phpcs --config-set colors 1

      - name: Log Debug Information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_EVENT_NAME"
          php --version
          mysql --version
          lsb_release -a
          ./vendor/bin/phpcs --version
          ./vendor/bin/phpcs -i

      - name: PHP Compatibility
        run: |
          ./vendor/bin/phpcs --standard=PHPCompatibility -p --runtime-set testVersion  5.6- ./index.php ./utm-dot-codes.php ./classes

      - name: WordPress Code Standards
        run: |
          ./vendor/bin/phpcs --standard=WordPress --report=summary ./index.php ./utm-dot-codes.php ./classes
