name: PHPUnit Tests Nightly (Legacy 5.6)

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
    types: [closed]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test-php:
    name: WordPress ${{ matrix.wordpress-versions }} - PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      matrix:
        php-versions: [ '5.6' ]
        wordpress-versions: [ 'nightly' ]
        operating-system: [ ubuntu-20.04 ]
    env:
      UTMDC_BITLY_API: ${{secrets.UTMDC_BITLY_API}}
      UTMDC_REBRANDLY_API: ${{secrets.UTMDC_REBRANDLY_API}}
      UTMDC_PLUGIN_DIR: ${{secrets.UTMDC_PLUGIN_DIR}}

    steps:
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Setup PHP
        # Commit hash for v2.25.4: https://github.com/shivammathur/setup-php/releases/tag/2.25.4
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug

      - name: Log Debug Information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_EVENT_NAME"
          php --version
          mysql --version
          lsb_release -a

      - name: Checkout utm.codes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install PHPUnit
        run: |
          composer require phpunit/phpunit:^5 --update-with-dependencies

      - name: Install WordPress
        run: |
          bash _test/bin/install-wp-tests.sh wordpress_test root root localhost:3306 ${{ matrix.wordpress-versions }}

      - name: Run PHPUnit Tests
        run: |
          cd _test
          ../vendor/bin/phpunit
